/**
 * Генерирует config.js из переменных окружения Vercel при деплое.
 * Local: node generate-config.js
 */
const fs = require('fs');
const path = require('path');

function env(name, fallback) {
  return process.env[name] || fallback;
}

function jsString(val) {
  if (val === null || val === undefined || val === '') return 'null';
  return JSON.stringify(String(val));
}

const siteUrl = env('SITE_URL', 'https://fleetpilot.ru').replace(/\/$/, '');
const supportEmail = env('SUPPORT_EMAIL', 'hello@fleetpilot.ru');

const config = `/**
 * Auto-generated by generate-config.js — do not edit on production.
 */
window.FLEETPILOT_CONFIG = {
  formspreeId: ${jsString(env('FORMSPREE_ID', 'YOUR_FORMSPREE_ID'))},
  formSubmitEmail: ${jsString(env('FORM_SUBMIT_EMAIL', supportEmail))},
  yandexMetrikaId: ${env('YANDEX_METRIKA_ID') ? env('YANDEX_METRIKA_ID') : 'null'},
  ga4MeasurementId: ${jsString(env('GA4_MEASUREMENT_ID', null))},
  siteName: 'FleetPilot',
  siteUrl: ${jsString(siteUrl)},
  supportEmail: ${jsString(supportEmail)},
};
`;

const out = path.join(__dirname, 'config.js');
fs.writeFileSync(out, config, 'utf8');
console.log('Generated', out);
